### ISSUE TITLE
Office format tests too slow

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/jtrTestSuite#38]
This is insane
```
form=office_2007                  guesses: 1500 0:00:20:21 DONE  [PASSED]
.pot CHK:office_2007              guesses: 1500 0:00:17:17 DONE  [PASSED]
```
We should run like 50 of them instead, for a 300x faster run.

**Comment by jfoug** [comment]
Sorry, I have not gotten office2007 checked in yet, but should.  I think it takes 5-10 seconds with proper salt-dupe logic.  NOTE, dupe salts are probably only theoretical (built for the TS).  I doubt that the change will make any difference ITW. 

Let me get those changes in, and then retest this.

**Comment by jfoug** [comment]
There are only 10 salts in the file (I think), with 150 passwords per salt.

**Comment by jfoug** [comment]
$ ./jtrts.pl office_2007
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper password cracker, version 1.8.0.2-jumbo-1-bleeding_omp [cygwin 64-bit XOP-autoconf]
--------------------------------------------------------------------------------

John Jumbo build detected.

form=office_2007                  guesses: 1500 0:00:00:08 DONE  [PASSED]
.pot CHK:office_2007              guesses: 1500 0:00:00:07 DONE  [PASSED]

All tests passed without error.  Performed 1 tests.  Time used was 25 seconds

**Comment by magnumripper** [comment]
That's a bit faster :)  Please do it to the OpenCL format too. No wait, they already use shared code right? Payoff again!

**Comment by magnumripper** [comment]
Hmm now it seems to be testing Office2010-opencl (also forever, this must be shrinked to like 5-10 hashes) but I did not see any such test for the CPU format?

**Comment by magnumripper** [comment]
I fear this will take hours. I give up this test run :-(

**Comment by jfoug** [comment]
I did not add (full) to the opencl. That is likely what needs to happen.  

The CPU uses common code for all office formats. The opencl has a unique format for each type. On the CPU side, I simply made the 2010,13 to be (full) types. I checked them to make sure they were happy, then simply set them up to run only in (full) mode.  We may want to add (full) for the opencl, or like you said, reduce the size of the input file greatly.

I do not believe that we can use the same 'trick' on 2010/13 as I found on the 07.   On the 10/13 there is a change thrown in that decouples us from the original data. So there is no way to do it in reverse and gain anything from the salts.

**Comment by magnumripper** [comment]
Placing them in 'full' will likely result in me never running them, which is not that good. I'd much prefer slimmed test files. Perhaps we could do both, with "full" running a somewhat more complete test?

For now I ran "internal" which is Good Stuff!!

**Comment by jfoug** [comment]
> Please do it to the OpenCL format too. No wait, they already use shared code right? Payoff again!

No, office07 does share a little, but just a little code.  It was due to design. There are 3 formats for GPU, but a 'merged' format for CPU.  The binary was shared (although I did have to add a check and ONLY allow it to run for office_2007).  

I have cut down 2010 and 2013 to 48 hashes (6 passwords for 8 salts, but in the end it is simply 48 independent salts).   I have also changed the 'unified' office input file (CPU only), to be the 48+48 and the rest filled in with 2007 hashes.  This one runs in a minute or 2 (for test/pot check), so it was still left (full).  The other 3 (cpu) are now acceptable.   Now, for GPU, 2007 runs on my box 6s (quick).  The 2010 runs in 1:04/1:03 (slow but usable). 2013 is still running, it might be hung.  But my crappy laptop GPU sux for testing 64 bit sha stuff.

I will check in these changes.

The
